// Mock Users - 12 total: 1 Admin, 2 Staff, 5 Scholars, 4 Applicants
export const mockUsers = [
  // Admin
  {
    id: 1,
    firstName: "Admin",
    lastName: "KKFI",
    email: "admin@kkfi.org",
    password: "Admin123",
    role: "admin",
    scholarshipType: null,
    status: "active",
    applicationStatus: null,
    createdAt: "2024-01-15T08:00:00Z",
  },
  // Staff
  {
    id: 2,
    firstName: "Maria",
    lastName: "Santos",
    email: "maria.santos@kkfi.org",
    password: "Staff123",
    role: "staff",
    scholarshipType: null,
    status: "active",
    applicationStatus: null,
    createdAt: "2024-02-10T09:00:00Z",
  },
  {
    id: 3,
    firstName: "Juan",
    lastName: "Dela Cruz",
    email: "juan.delacruz@kkfi.org",
    password: "Staff123",
    role: "staff",
    scholarshipType: null,
    status: "active",
    applicationStatus: null,
    createdAt: "2024-03-05T10:00:00Z",
  },
  // Scholars
  {
    id: 4,
    firstName: "Ana",
    lastName: "Reyes",
    email: "ana.reyes@scholar.kkfi.org",
    password: "Scholar123",
    role: "scholar",
    scholarshipType: "Tertiary",
    status: "active",
    applicationStatus: "approved",
    createdAt: "2024-04-20T11:00:00Z",
  },
  {
    id: 5,
    firstName: "Carlos",
    lastName: "Garcia",
    email: "carlos.garcia@scholar.kkfi.org",
    password: "Scholar123",
    role: "scholar",
    scholarshipType: "Vocational",
    status: "active",
    applicationStatus: "approved",
    createdAt: "2024-05-15T12:00:00Z",
  },
  {
    id: 6,
    firstName: "Beatrice",
    lastName: "Lim",
    email: "beatrice.lim@scholar.kkfi.org",
    password: "Scholar123",
    role: "scholar",
    scholarshipType: "SDEA",
    status: "inactive",
    applicationStatus: "approved",
    createdAt: "2024-06-10T13:00:00Z",
  },
  {
    id: 7,
    firstName: "Daniel",
    lastName: "Tan",
    email: "daniel.tan@scholar.kkfi.org",
    password: "Scholar123",
    role: "scholar",
    scholarshipType: "Board Exam Assistance",
    status: "active",
    applicationStatus: "approved",
    createdAt: "2024-07-01T14:00:00Z",
  },
  {
    id: 8,
    firstName: "Elena",
    lastName: "Villanueva",
    email: "elena.villanueva@scholar.kkfi.org",
    password: "Scholar123",
    role: "scholar",
    scholarshipType: "Tertiary",
    status: "active",
    applicationStatus: "approved",
    createdAt: "2024-08-25T15:00:00Z",
  },
  // Applicants
  {
    id: 9,
    firstName: "Franco",
    lastName: "Mendoza",
    email: "franco.mendoza@gmail.com",
    password: "Applicant123",
    role: "applicant",
    scholarshipType: "Tertiary",
    status: "active",
    applicationStatus: "pending",
    createdAt: "2025-01-10T08:30:00Z",
  },
  {
    id: 10,
    firstName: "Grace",
    lastName: "Aquino",
    email: "grace.aquino@gmail.com",
    password: "Applicant123",
    role: "applicant",
    scholarshipType: "Vocational",
    status: "active",
    applicationStatus: "under review",
    createdAt: "2025-01-15T09:45:00Z",
  },
  {
    id: 11,
    firstName: "Henry",
    lastName: "Bautista",
    email: "henry.bautista@gmail.com",
    password: "Applicant123",
    role: "applicant",
    scholarshipType: "SDEA",
    status: "active",
    applicationStatus: "pending",
    createdAt: "2025-02-01T10:15:00Z",
  },
  {
    id: 12,
    firstName: "Isabelle",
    lastName: "Ramos",
    email: "isabelle.ramos@gmail.com",
    password: "Applicant123",
    role: "applicant",
    scholarshipType: "Tertiary",
    status: "active",
    applicationStatus: "under review",
    createdAt: "2025-02-20T11:00:00Z",
  },
];

// Mock Scholarship Programs
export const mockPrograms = [
  {
    id: 1,
    name: "Tertiary Education Scholarship",
    description:
      "A comprehensive scholarship program supporting college students pursuing four-year degree programs in accredited universities and colleges across the Philippines. This program covers tuition, miscellaneous fees, and provides a monthly stipend to help scholars focus on their academic pursuits.",
    eligibility:
      "Must be a Filipino citizen, enrolled in an accredited college or university, maintaining a GPA of at least 2.0, and with a combined family annual income not exceeding ₱300,000.",
    requirements: [
      "Certified true copy of grades from the previous semester",
      "Certificate of enrollment for the current semester",
      "Certificate of good moral character",
      "Proof of family income (ITR or Certificate of Indigency)",
      "2x2 ID photo (recent)",
      "Photocopy of valid ID",
    ],
    benefits: [
      "Full tuition fee coverage",
      "Monthly stipend of ₱3,000",
      "Book and supplies allowance of ₱5,000 per semester",
      "Annual educational assistance",
      "Access to KKFI mentorship programs",
    ],
  },
  {
    id: 2,
    name: "Vocational Training Scholarship",
    description:
      "Designed for students enrolled in TESDA-accredited vocational and technical courses. This program helps learners acquire practical skills and certifications that improve their employability and capacity for productive work.",
    eligibility:
      "Must be a Filipino citizen, at least 18 years old, enrolled in a TESDA-accredited institution, and with a combined family annual income not exceeding ₱200,000.",
    requirements: [
      "Certificate of enrollment in TESDA-accredited course",
      "TESDA assessment result (if applicable)",
      "Certificate of good moral character",
      "Proof of family income",
      "2x2 ID photo (recent)",
      "Barangay clearance",
    ],
    benefits: [
      "Full training fee coverage",
      "Daily transportation allowance",
      "Tools and equipment allowance",
      "TESDA assessment fee coverage",
      "Job placement assistance upon completion",
    ],
  },
  {
    id: 3,
    name: "SDEA (Socially Disadvantaged Educational Assistance)",
    description:
      "A special assistance program for students from socially disadvantaged backgrounds, including indigenous peoples, persons with disabilities, and those from conflict-affected areas. The program provides holistic support to ensure equitable access to quality education.",
    eligibility:
      "Must belong to a socially disadvantaged group (indigenous peoples, PWDs, conflict-affected communities), enrolled in any accredited educational institution, and meet the income threshold of ₱150,000 combined family annual income.",
    requirements: [
      "Proof of membership in a socially disadvantaged group",
      "Certificate of enrollment",
      "Medical certificate (for PWD applicants)",
      "Tribal/community leader certification (for IP applicants)",
      "Proof of family income",
      "Personal essay (500 words minimum)",
    ],
    benefits: [
      "Full tuition coverage",
      "Monthly living allowance of ₱4,000",
      "Special needs support (assistive devices, interpreters, etc.)",
      "Counseling and psychosocial support",
      "Community engagement opportunities",
    ],
  },
  {
    id: 4,
    name: "Board Exam Assistance",
    description:
      "Financial assistance for graduating scholars and alumni preparing for professional licensure examinations. The program covers review center fees and examination costs to help scholars achieve professional licensure.",
    eligibility:
      "Must be a current KKFI scholar or alumni, graduating or recently graduated (within 1 year), and registered for a PRC board examination.",
    requirements: [
      "Proof of graduation or certification of candidacy for graduation",
      "PRC board exam application or registration",
      "Review center enrollment proof",
      "Endorsement letter from KKFI program coordinator",
      "Updated resume/CV",
    ],
    benefits: [
      "Review center fee coverage (up to ₱15,000)",
      "Board exam registration fee",
      "Transportation allowance during review period",
      "Study materials allowance",
      "Post-exam career counseling",
    ],
  },
];
