export const mockUsers = [
  {
    id: 1,
    firstName: "Maria",
    lastName: "Cruz",
    email: "maria.cruz@example.com",
    password: "Default123",
    role: "admin",
    scholarshipType: null,
    status: "active",
    applicationStatus: null,
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: 2,
    firstName: "Juan",
    lastName: "Dela Rosa",
    email: "juan.delarosa@example.com",
    password: "Default123",
    role: "staff",
    scholarshipType: null,
    status: "active",
    applicationStatus: null,
    createdAt: "2026-01-06T10:00:00.000Z",
  },
  {
    id: 3,
    firstName: "Ana",
    lastName: "Reyes",
    email: "ana.reyes@example.com",
    password: "Default123",
    role: "scholar",
    scholarshipType: "Tertiary",
    status: "active",
    applicationStatus: "approved",
    createdAt: "2026-01-07T10:00:00.000Z",
  },
  {
    id: 4,
    firstName: "Carlo",
    lastName: "Navarro",
    email: "carlo.navarro@example.com",
    password: "Default123",
    role: "applicant",
    scholarshipType: "Vocational",
    status: "inactive",
    applicationStatus: "pending",
    createdAt: "2026-01-08T10:00:00.000Z",
  },
];

